version: '3.9'
services:
  app:
    container_name: docker_rails_app
    build:
      context: .
    env_file:
      - ./infrastructure/mysql/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/base_app
      - public-data:/base_app/public
      - tmp-data:/base_app/tmp
      - log-data:/base_app/log
    depends_on:
      - db
  db:
    image: mysql:8.0.26
    env_file:
      - ./infrastructure/mysql/db.env
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: ./infrastructure/nginx
      dockerfile: ./Dockerfile
    volumes:
      - public-data:/base_app/public
      - tmp-data:/base_app/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: